name: "web-rtc-project"
services:
  # Jitsi Web Interface
  jitsi-web:
    image: jitsi/web
    container_name: jitsi-web
    restart: unless-stopped
    ports:
      - "8443:8443"
      - "443:443"
      - "80:80"
    environment:
      - PUBLIC_URL=http://localhost
      - ENABLE_XMPP_WEBSOCKET=1
    depends_on:
      - jitsi-prosody
      - jitsi-jicofo
      - jitsi-videobridge

  # XMPP Server for Jitsi
  jitsi-prosody:
    image: jitsi/prosody
    container_name: jitsi-prosody
    restart: unless-stopped
    environment:
      - XMPP_DOMAIN=meet.jitsi
      - XMPP_AUTH_DOMAIN=auth.meet.jitsi
      - XMPP_MUC_DOMAIN=muc.meet.jitsi
      - XMPP_INTERNAL_MUC_DOMAIN=internal-muc.meet.jitsi

  # Jicofo (Conference Focus Component)
  jitsi-jicofo:
    image: jitsi/jicofo
    container_name: jitsi-jicofo
    restart: unless-stopped
    environment:
      - XMPP_SERVER=xmpp.meet.jitsi
      - JICOFO_AUTH_USER=focus
      - JICOFO_AUTH_PASSWORD=securepassword

  # Jitsi Video Bridge
  jitsi-videobridge:
    image: jitsi/jvb
    container_name: jitsi-videobridge
    restart: unless-stopped
    ports:
      - "10000:10000/udp"
    environment:
      - XMPP_SERVER=xmpp.meet.jitsi
      - JVB_STUN_SERVERS=stun:stun.l.google.com:19302
      - JVB_PORT=10000
      - JVB_TCP_HARVESTER_DISABLED=true
